# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]

    app.app_utils:
        class: AppBundle\Utils\AppUtils
        arguments: [@doctrine]

    app.geo_utils:
        class: AppBundle\Utils\GeoUtils

    app.main_menu:
            class: Knp\Menu\MenuItem
            factory_service: app.menu_builder
            factory_method: createMainMenu
            arguments: ["@security.context"]
            tags:
                - { name: knp_menu.menu, alias: main }

    app.comparison_menu:
            class: Knp\Menu\MenuItem
            factory_service: app.menu_builder
            factory_method: createComparisonMenu
            arguments: [@request_stack, @doctrine.orm.entity_manager]
            tags:
                - { name: knp_menu.menu, alias: comparison_menu }

    app.comparison_listener:
      class: AppBundle\Listener\ComparisonListener
      tags:
        - { name : doctrine.event_listener, event : onFlush }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
