AppBundle\Entity\ComparisonCaseCalc:
  type: entity
  table: comparison_case_calc
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    citypair:
      type: string
      length: 50
    cost:
      type: integer
    time:
      type: time
    route:
      type: text
      nullable: true
  manyToOne:
    case:
      targetEntity: AppBundle\Entity\ComparisonCase
      inversedBy: calcs
      joinColumn:
        name: case_id
        referencedColumnName: id
