AppBundle\Entity\Flightwatch:
    type: entity
    table: flightwatch
    repositoryClass: AppBundle\Entity\FlightwatchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        flightNumber:
            type: string
            length: 255
            column: flight_number
        dep:
            type: string
        dest:
            type: string
        flightDate:
            type: date
            column: flight_date
        std:
            type: time
        takeOffTime:
            type: datetime
            column: takeoff_time
            nullable: true
        altn:
          type: string
        erd:
          type: string
          nullable: true
        erda:
          type: string
          nullable: true
        completed:
          type: boolean
          nullable: true
          options:
            default: false
        completed_at:
          type: datetime
          nullable: true
        completed_by:
          type: string
          nullable: true
        desk:
          type: integer
          nullable: false
    oneToMany:
          info:
            targetEntity: AppBundle\Entity\FlightwatchInfo
            mappedBy: flight
            orphanRemoval: true
            cascade: ['remove']
