AppBundle\Entity\HighSpeedFuel:
  type: entity
  table: high_speed_fuel
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    date:
      type: date
    flightNumber:
      type: string
      length: 7
      column: flight_number
    depIATA:
      type: string
      length: 3
      column: dep_iata
      nullable: true
    destIATA:
      type: string
      length: 3
      column: dest_iata
      nullable: true
    normalFlightTime:
      type: time
      nullable: true
    highSpeedFlightTime:
      type: time
      nullable: true
    normalCost:
      type: integer
      nullable: true
    highSpeedCost:
      type: integer
      nullable: true
    archived:
      type: boolean
      nullable: true




