AppBundle\Entity\ShiftLogFiles:
    type: entity
    table: shift_log_files
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        file_name:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
