AppBundle\Entity\ShiftLog:
    type: entity
    table: shift_log
    repositoryClass: AppBundle\Entity\ShiftLogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        infoType:
            type: string
            length: 255
            column: info_type
        infoHeader:
            type: string
            length: 255
            column: info_header
        content:
            type: text
            nullable: true
        sequence:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
