AppBundle\Entity\ShiftLogArchive:
    type: entity
    table: shift_log_archive
    repositoryClass: AppBundle\Entity\ShiftLogArchiveRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: array
            nullable: true
        archivedDate:
            type: date
            column: archived_date
            nullable: true
        archivedShift:
            type: string
            column: archived_shift
            length: 255
            nullable: true
        archivedBy:
            type: string
            column: archived_by
            nullable: true
        onShift:
            type: array
            column: on_shift
            nullable: true
    lifecycleCallbacks: {  }
