AppBundle\Entity\Waypoints:
  type: entity
  table: waypoints
  repositoryClass: WaypointsRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    wpt_id:
      type: string
      length: 50
    lat:
      type: float
    lon:
      type: float
